# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b8bf536fd4cc406cc1a49f0ec0779ecbc08da10cfe28ada73bd01d30fd2e2640f9fea92ad390f39522f3391482beab17bd250fc54f7d7ac864f758962effd2f

test:
  secret_key_base: a7f6f0cc82db995f1248506f2028824823b15cef242e513b09702e1eda2c9554dd04b17b0fa8293586d45d9d3602b1363bfd3300826717f11dd9aac3e5440abe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
